/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.example.combotooldoihotro.views.views;

import org.example.combotooldoihotro.config.UserLogin;
import org.example.combotooldoihotro.rootDTO.IpAddRestDTO;
import org.example.combotooldoihotro.rootEntites.IPLogin;
import org.example.combotooldoihotro.rootEntites.IpDevice;
import org.example.combotooldoihotro.rootEntites.TableKey;
import org.example.combotooldoihotro.rootImplements.GetAPIImplement;
import org.example.combotooldoihotro.rootServices.GetAPIService;
import org.example.combotooldoihotro.views.ui.EditButtons;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author ADMIN
 */
public class Login extends JDialog {
    GetAPIService getAPIService = new GetAPIImplement();
    EditButtons editButtons = new EditButtons();
    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        ImageIcon icon = new ImageIcon("./logo256.jpg"); // Đường dẫn đến file icon
        setIconImage(icon.getImage());
        setTitle("256 Green Color Login");
        setResizable(false);
        setLocationRelativeTo(null);
        editButtons.Edit(btnExit);
        editButtons.Edit(btnLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jPanelBackground2 = new org.example.combotooldoihotro.views.ui.JPanelBackground();
        jPanel3 = new JPanel();
        jLabel1 = new JLabel();
        btnExit = new JButton();
        txtCode = new JTextField();
        jLabel2 = new JLabel();
        btnLogin = new JButton();
        jLabel3 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        GroupLayout jPanelBackground2Layout = new GroupLayout(jPanelBackground2);
        jPanelBackground2.setLayout(jPanelBackground2Layout);
        jPanelBackground2Layout.setHorizontalGroup(
            jPanelBackground2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        jPanelBackground2Layout.setVerticalGroup(
            jPanelBackground2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Code active:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        btnExit.setBackground(new java.awt.Color(50, 194, 45));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, 50));

        txtCode.setBorder(null);
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        jPanel3.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 430, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 194, 45));
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Đăng Nhập");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 213, -1));

        btnLogin.setBackground(new java.awt.Color(50, 194, 50));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Vào");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, 50));

        jLabel3.setText("________________________________________________________");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 420, 30));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBackground2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanelBackground2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String key = txtCode.getText().trim();
        List<TableKey> tableKeys = getAPIService.getAllKey();
        TableKey tableKeyCheck = new TableKey();

        txtCode.setEnabled(false);
        btnExit.setEnabled(false);
        btnLogin.setEnabled(false);

        for (TableKey tableKey: tableKeys) {
            tableKeyCheck.setKeyword(tableKey.getKeyword());
            tableKeyCheck.setStatus(tableKey.getStatus());
        }

        if(key.equals(tableKeyCheck.getKeyword()) && tableKeyCheck.getStatus() == 1) {
            IpAddRestDTO ipAddRestDTO = getAPIService.getIpAddRest();
            System.out.println(ipAddRestDTO.toString());

            for (IPLogin ipLoginCheck :getAPIService.getAllIpLogin()) {
                if((ipLoginCheck.getIpLogin() == ipAddRestDTO.getIp()) && ipLoginCheck.getStatus() == 0) {
                    JOptionPane.showMessageDialog(this, "IP của bạn đang bị chặn, muốn mở khóa hãy liên hệ quản trị vên!");
                    txtCode.setEnabled(true);
                    btnExit.setEnabled(true);
                    btnLogin.setEnabled(true);
                    return;
                }
            }

            for (IpDevice ipDeviceCheck :getAPIService.getAllIpDevice()) {
                if((ipDeviceCheck.getIpDevice() == ipAddRestDTO.getIdDevice()) && ipDeviceCheck.getStatus() == 0) {
                    JOptionPane.showMessageDialog(this, "Thiết bị của bạn đang bị chặn, muốn mở khóa hãy liên hệ quản trị vên!");
                    txtCode.setEnabled(true);
                    btnExit.setEnabled(true);
                    btnLogin.setEnabled(true);
                    return;
                }
            }
            getAPIService.getAddIp();
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công.");
            UserLogin.getUserLogin().setCode(key);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(this, "Key không đúng hoặc đã hết hạn!");
            txtCode.setEnabled(true);
            btnExit.setEnabled(true);
            btnLogin.setEnabled(true);
            return;
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnExit;
    private JButton btnLogin;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private org.example.combotooldoihotro.views.ui.JPanelBackground jPanelBackground2;
    private JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
