package org.example.combotooldoihotro.views.views;

import org.example.combotooldoihotro.BaseAll;
import org.example.combotooldoihotro.config.UserLogin;
import org.example.combotooldoihotro.mainSwing.CheckSoldShop.MainCheckSold;
import org.example.combotooldoihotro.rootDTO.IpAddRestDTO;
import org.example.combotooldoihotro.rootEntites.IPLogin;
import org.example.combotooldoihotro.rootEntites.IpDevice;
import org.example.combotooldoihotro.rootEntites.TableKey;
import org.example.combotooldoihotro.rootImplements.GetAPIImplement;
import org.example.combotooldoihotro.rootServices.GetAPIService;
import org.example.combotooldoihotro.views.ui.EditButtons;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ADMIN
 */
public class NewJFrame extends JFrame {
    MainCheckSold mainCheckSold = new MainCheckSold();
    String userDataPath = "";
    boolean checkSearchEngine = false;
    boolean checkProfile = false;
    BaseAll baseAll = new BaseAll();
    private Login login;

    GetAPIService getAPIService = new GetAPIImplement();

    private EditButtons editButtons = new EditButtons();

    public NewJFrame() {
        initComponents();
        ImageIcon icon = new ImageIcon("./logo256.jpg"); // Đường dẫn đến file icon
        setIconImage(icon.getImage());
        setTitle("256 Green Color Tool Company");
        // Tắt tính năng thay đổi kích thước (tắt nút phóng to)
        setResizable(false);
        setLocationRelativeTo(null);
        // Lấy thông tin hệ điều hành hiện tại
        login = new Login(this, rootPaneCheckingEnabled);
        login.setVisible(true);

        this.getUserData();
        profile.setText(checkSearchEngine == false ? findDefaultFirefoxProfileName(userDataPath) : "");
        this.setPreferredSize(new Dimension(1011, 489));
        userData.setText(userDataPath);
        editButtons.EditNoneBorder(toolCheckSold);
        editButtons.EditNoneBorder(toolCheckSold);
    }

    public void getUserData() {
        String os = System.getProperty("os.name").toLowerCase();

        if (os.contains("win")) {
            // Windows
            userDataPath = System.getProperty("user.home") + (checkSearchEngine == false ? "\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles" : "\\AppData\\Local\\Google\\Chrome\\User Data");
            System.out.println("Đường dẫn userdata Firefox trên Windows: " + userDataPath);
        }
        else {
            System.out.println("Hệ điều hành không xác định!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        buttonGroupVersionBrowser = new javax.swing.ButtonGroup();
        buttonGroupCheckProfile = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnThongTinTool = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        toolCheckSold = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(50, 194, 45)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(50, 194, 45));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("256 Green Tool");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 194, 45)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tên Profile:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        profile.setBorder(null);

        jPanel4.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 350, 20));

        jLabel2.setText("Nơi lưu trữ:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        userData.setBorder(null);

        jPanel4.add(userData, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 350, 20));

        jLabel3.setText("__________________________________________________");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 350, -1));

        jLabel5.setText("__________________________________________________");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 350, -1));

        buttonGroupVersionBrowser.add(jRadioButton1);
        jRadioButton1.setText("Chrome");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel6.setText("Loại profile:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        buttonGroupVersionBrowser.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("FireFox");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel7.setText("Loại trình duyệt:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        buttonGroupCheckProfile.add(jRadioButton3);
        jRadioButton3.setText("Không dùng profile");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        buttonGroupCheckProfile.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("Có dùng profile");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        btnThongTinTool.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThongTinTool.setText("Thông tin tool");
        btnThongTinTool.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnThongTinToolAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(btnThongTinTool, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 80, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolCheckSold.setText("check sold shop");
        toolCheckSold.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        toolCheckSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolCheckSoldActionPerformed(evt);
            }
        });
        jPanel7.add(toolCheckSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        checkSearchEngine = true;
        this.getUserData();
        profile.setText(checkSearchEngine == false ? findDefaultFirefoxProfileName(userDataPath) : "");
        userData.setText(userDataPath);
    }

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        checkSearchEngine = false;
        this.getUserData();
        profile.setText(checkSearchEngine == false ? findDefaultFirefoxProfileName(userDataPath) : "");
        userData.setText(userDataPath);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        checkProfile = true;
        this.getUserData();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        checkProfile = false;
        this.getUserData();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnThongTinToolAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnThongTinToolAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongTinToolAncestorAdded

    private void toolCheckSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolCheckSoldActionPerformed
         boolean checkProfileSuccess = checkIfProfileExists(profile.getText());
        if (checkProfileSuccess == false) {
            baseAll.showMessageDone("Profile không tồn tại!");
            return;
        }
        disableAllInputsAndButtons(false);
        mainCheckSold.mainStart(checkSearchEngine, checkProfile, profile.getText(), userData.getText());
        baseAll.showMessageDone("Đã kiểm tra xong");
        getValidateKey();
        disableAllInputsAndButtons(true);
    }//GEN-LAST:event_toolCheckSoldActionPerformed

    public boolean checkIfProfileExists(String profileName) {
        if (checkProfile == true) {
            return true;
        }
        // Quét thư mục chứa các profile Google Chrome (địa chỉ thư mục có thể thay đổi tùy hệ điều hành)
        File profilesDirectory = new File(userData.getText());
        // Kiểm tra nếu thư mục không tồn tại
        if (!profilesDirectory.exists() || !profilesDirectory.isDirectory()) {
            JOptionPane.showMessageDialog(null, "Thư mục chứa Profiles không tồn tại.");
            return false;
        }
        // Tạo đối tượng File cho Profile 1
        File profile = new File(profilesDirectory, profileName); // Tạo đối tượng File với tên Profile
        // Kiểm tra nếu thư mục Profile tồn tại
        return profile.exists() && profile.isDirectory(); // Nếu tồn tại và là thư mục thì trả về true
    }

    public void disableAllInputsAndButtons(Boolean check) {
        // Vô hiệu hóa các ô nhập liệu
        profile.setEnabled(check);
        userData.setEnabled(check);
        // Vô hiệu hóa các nút

        toolCheckSold.setEnabled(check);
    }

    public static String findDefaultFirefoxProfileName(String profilesRootPath) {
        File profilesDir = new File(profilesRootPath);
        if (!profilesDir.exists() || !profilesDir.isDirectory()) {
            System.out.println("Thư mục Profiles Firefox không tồn tại: " + profilesRootPath);
            return null;
        }

        File[] profileDirs = profilesDir.listFiles(File::isDirectory);
        if (profileDirs == null || profileDirs.length == 0) {
            System.out.println("Không tìm thấy thư mục profile nào trong: " + profilesRootPath);
            return null;
        }

        for (File profileDir : profileDirs) {
            String name = profileDir.getName();
            // Kiểm tra tên phải kết thúc chính xác bằng ".default-release"
            if (name.endsWith(".default-release")) {
                System.out.println("Tìm thấy profile chính xác: " + name);
                return name;
            }
        }

        System.out.println("Không tìm thấy profile kết thúc bằng '.default-release', sử dụng profile đầu tiên: " + profileDirs[0].getName());
        return profileDirs[0].getName();
    }

    public void getValidateKey() {
        String key = UserLogin.getUserLogin().getCode();
        List<TableKey> tableKeys = getAPIService.getAllKey();
        TableKey tableKeyCheck = new TableKey();

        for (TableKey tableKey : tableKeys) {
            tableKeyCheck.setKeyword(tableKey.getKeyword());
            tableKeyCheck.setStatus(tableKey.getStatus());
        }

        if (key.equals(tableKeyCheck.getKeyword()) && tableKeyCheck.getStatus() == 1) {
            IpAddRestDTO ipAddRestDTO = getAPIService.getIpAddRest();
            System.out.println(ipAddRestDTO.toString());
            getAPIService.getAddIp();

            for (IPLogin ipLoginCheck : getAPIService.getAllIpLogin()) {
                if (ipLoginCheck.getIpLogin() == ipAddRestDTO.getIp() && ipLoginCheck.getStatus() == 0) {
                    JOptionPane.showMessageDialog(this, "IP của bạn đang bị chặn, muốn mở khóa hãy liên hệ quản trị vên!");
                    System.exit(0);
                }
            }

            for (IpDevice ipDeviceCheck : getAPIService.getAllIpDevice()) {
                if (ipDeviceCheck.getIpDevice() == ipAddRestDTO.getIdDevice() && ipDeviceCheck.getStatus() == 0) {
                    JOptionPane.showMessageDialog(this, "Thiết bị của bạn đang bị chặn, muốn mở khóa hãy liên hệ quản trị vên!");
                    System.exit(0);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Key không đúng hoặc đã hết hạn!");
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnThongTinTool;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupCheckProfile;
    private javax.swing.ButtonGroup buttonGroupVersionBrowser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField profile;
    private javax.swing.JButton toolCheckSold;
    private javax.swing.JTextField userData;
    // End of variables declaration//GEN-END:variables
}
